language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade -r requirements.txt

script:
  - flake8
  - pytest fizzbuzz/*.py countcapitalletters/*.py catdogyears/*.py
